name = "WeightNormalizedRBMs"
uuid = "22ec42ac-8696-41f9-9be6-2703ea0aa0ae"
authors = ["Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"]
version = "0.2.0"

[deps]
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"

[compat]
Optimisers = "0.4"
RestrictedBoltzmannMachines = "7.1"
julia = "1.12"

[workspace]
projects = ["test", "docs"]
